package com.xiaomi.gamecenter.sdk.entry;

/* loaded from: classes3.dex */
public enum MiGravity {
    MI_TOP_LEFT,
    MI_TOP_RIGHT,
    MI_BOTTOM_LEFT,
    MI_BOTTOM_RIGHT,
    MI_TOP_CENTER,
    MI_LEFT_CENTER,
    MI_RIGHT_CENTER,
    MI_BOTTOM_CENTER,
    MI_TOP_CENTER_LEFT,
    MI_TOP_CENTER_RIGHT,
    MI_LEFT_CENTER_TOP,
    MI_LEFT_CENTER_BOTTOM,
    MI_RIGHT_CENTER_TOP,
    MI_RIGHT_CENTER_BOTTOM,
    MI_BOTTOM_CENTER_LEFT,
    MI_BOTTOM_CENTER_RIGHT
}
