package com.adobe.creativesdk.foundation.storage;

import com.adobe.creativesdk.foundation.adobeinternal.storage.psd.AdobePSDCompositeLayerBlendOptionsMode;

/* compiled from: AdobePSDLayerNode.java */
/* renamed from: com.adobe.creativesdk.foundation.storage.ac */
/* loaded from: classes.dex */
public class C0536ac {

    /* renamed from: a */
    private static AdobePSDCompositeLayerBlendOptionsMode[] f7199a = {AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeNormal, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeDissolve, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeDarken, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeMultiply, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeColorBurn, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLinearBurn, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeDarkerColor, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLighten, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeScreen, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeColorDodge, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLinearDodge, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLighterColor, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeOverlay, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeSoftLight, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeHardLight, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeVividLight, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLinearLight, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModePinLight, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeHardMix, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeDifference, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeExclusion, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeSubtract, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeDivide, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeHue, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeSaturation, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeColor, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModeLuminosity, AdobePSDCompositeLayerBlendOptionsMode.AdobePSDCompositeLayerBlendOptionsModePassThrough};

    /* renamed from: b */
    protected com.adobe.creativesdk.foundation.adobeinternal.storage.dcx.Ha f7200b;

    public com.adobe.creativesdk.foundation.adobeinternal.storage.dcx.Ha a() {
        return this.f7200b;
    }
}
