package com.nexstreaming.kinemaster.ui.settings;

import android.app.AlertDialog;
import android.content.DialogInterface;

/* compiled from: SettingFragment.java */
/* loaded from: classes.dex */
class ac implements DialogInterface.OnClickListener {

    /* renamed from: a, reason: collision with root package name */
    final /* synthetic */ String f4233a;
    final /* synthetic */ aa b;

    /* JADX INFO: Access modifiers changed from: package-private */
    public ac(aa aaVar, String str) {
        this.b = aaVar;
        this.f4233a = str;
    }

    @Override // android.content.DialogInterface.OnClickListener
    public void onClick(DialogInterface dialogInterface, int i) {
        StringBuilder sb = new StringBuilder("#auto-generated by km config manager\n");
        sb.append("#selected installer").append("\n").append("INAPP_INSTALLER=" + this.f4233a).append("\n");
        switch (i) {
            case 1:
                sb.append("#inapp using test server").append("\n").append("INAPP_TEST=true").append("\n");
                break;
        }
        new AlertDialog.Builder(this.b.f4231a).setTitle("Choose SKU type").setCancelable(false).setItems(new String[]{"Real", "Test"}, new ae(this, sb)).setNegativeButton("Cancel", new ad(this)).show();
    }
}
